# Starter pipeline
name: Synopsys-GitHub-CI

# Controls when the workflow will run
#on:
 #Triggers the workflow on push or pull request events but only for the main branch
 # push:
 #   branches: [ '**' ]
 # pull_request:
 #   branches: [ master ]
    
# Allows you to run this workflow manually from the Actions tab
  workflow_dispatch: true

trigger:
- master

pool:
  vmImage: 'windows-latest'
variables: 
 solution: '**/*.sln'
 buildPlatform: 'Any CPU'
 buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1
- task: NuGetCommand@2
  Inputs: 
    restoreSolution: '$(solution)'
 
#- task: MSBuild@1
#  inputs:
#    

- task: SynopsysPolaris@1
  inputs:
    polarisService: 'Polaris-Csharp'
    polarisCommand: 'analyze -w --coverity-ignore-capture-failure '
 
 - task: SynopsysDetectTask@7
   inputs:
      BlackDuckService: 'Black Duck - Demo Cshap'
      DetectArguments: '--detect.policy.check.fail.on.severities=BLOCKER'
      DetectVersion: 'latest'
