# Starter pipeline

name: Synopsys-GitHub-CI

# Controls when the workflow will run
# on:
 #Triggers the workflow on push or pull request events but only for the main branch
 # push:
 #   branches: [ '**' ]
 # pull_request:
 #   branches: [ master ]
    
# Allows you to run this workflow manually from the Actions tab
 

trigger:
- master

pool:
  vmImage: 'windows-latest'
variables: 
 solution: '**/*.sln'
 buildPlatform: 'Any CPU'
 buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1
  inputs:
    command: 'restore'
    restoreSolution: '$(solution)'
    feedsToUse: 'select'
    verbosityRestore: 'Quiet'
 
#- task: MSBuild@1
#  inputs:
#    
 
- task: SynopsysSecurityScan@1
  inputs:
    scanType: 'polaris'
    bridge_polaris_serverUrl: 'https://poc.polaris.synopsys.com`'
    bridge_polaris_accessToken: 'wefrwerewr'
    bridge_polaris_application_name: 'ajw-doris'
    bridge_polaris_project_name: 'abc'
    bridge_polaris_assessment_types: 'SAST,SCA'
    bridge_polaris_branch_name: 'master'
    polarisPRCommentEnabled: true
    polarisPRCommentSeverities: 'criticial'
    polarisReportsSarifCreate: true
    polarisReportsSarifSeverities: 'critical'
    polarisAssessmentMode: 'CI'
    #azure_token: ''
