# Starter pipeline
name: Synopsys-GitHub-CI

# Controls when the workflow will run
# on:
 #Triggers the workflow on push or pull request events but only for the main branch
 # push:
 #   branches: [ '**' ]
 # pull_request:
 #   branches: [ master ]
    
# Allows you to run this workflow manually from the Actions tab
 

trigger:
- master

pool:
  vmImage: 'windows-latest'
variables: 
 solution: '**/*.sln'
 buildPlatform: 'Any CPU'
 buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1
- task: NuGetCommand@2
  inputs: 
    restoreSolution: '$(solution)'
 
#- task: MSBuild@1
#  inputs:
#    

- task: SynopsysPolaris@1
  inputs:
     polarisService: 'Polaris-Csharp'
     polarisCommand: 'analyze -w --coverity-ignore-capture-failure '
 
- task: SynopsysDetectTask@7
  inputs:
     BlackDuckService: 'Black Duck - Demo Cshap'
     DetectArguments:
      --detect.policy.check.fail.on.severities=BLOCKER,CRITICAL
      --detect.policy.check.fail.on.names=xyz
      --detect.project.tier=1
      --detect.project.version.name=teste1'
     DetectVersion: 'latest'
