# Starter pipeline
name: Synopsys-GitHub-CI

# Controls when the workflow will run
# on:
 #Triggers the workflow on push or pull request events but only for the main branch
 # push:
 #   branches: [ '**' ]
 # pull_request:
 #   branches: [ master ]
    
# Allows you to run this workflow manually from the Actions tab
 

trigger:
- master

pool:
  vmImage: 'windows-latest'
variables: 
 solution: '**/*.sln'
 buildPlatform: 'Any CPU'
 buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1
  inputs:
    command: 'restore'
    restoreSolution: '$(solution)'
    feedsToUse: 'select'
    verbosityRestore: 'Quiet'
 
#- task: MSBuild@1
#  inputs:
#    

- task: SynopsysPolaris@1
  inputs:
    polarisService: 'Polaris-Demo'
    polarisCommand: 'analyze -w --coverity-ignore-capture-failure'
    populateChangeSetFile: true
 
- task: SynopsysDetectTask@7
  inputs:
    BlackDuckService: 'Partner-Demo'
    DetectArguments: '--detect.policy.check.fail.on.severities=BLOCKER --detect.policy.check.fail.on.names=xyz --detect.project.tier=1 --detect.project.name=JWCSharp --detect.project.version.name=teste21 --detect.blackduck.scan.mode=INTELLIGENT'
    DetectVersion: 'latest'
